### ISSUE TITLE
Migrate to new Trust wallet repository

### ISSUE THREAD

**Issue by cbovis** [0xTracker/0x-tracker-worker#325]
# Description
Trust wallet has migrated their assets to a new repository (https://github.com/trustwallet/assets). The old repository still exists which means 0x Tracker hasn't been negatively impacted but it does mean that we don't receive any new token images.

The job for fetching token images should be updated to use this new repository instead of the old one.

**Comment by gabririgo** [comment]
+1

**Comment by cbovis** [comment]
This has now been completed.
